GET http://localhost:8000/user

###

POST http://localhost:8000/user
Content-Type: application/json

{
    "name" : "soso"
}

###

PATCH  http://localhost:8000/user/1234

###


 // products routes

GET http://localhost:8000/product

###

POST http://localhost:8000/product
Content-Type: application/json

{
    "name" : "sneakers"
}