

// USERS ROUTES

GET http://localhost:8888/admin/users/all
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.dGVzdDFAZ21haWwuY29t.KuOSGmuCgiw59N8EaUVSZxxwmIzUJoHxzG6i3R6Rzz8

###
GET http://localhost:8888/admin/user/single62348a479cee35515846e475

    

###
POST  http://localhost:8888/admin/user/add
Content-Type: application/json

{
    "username": "test7",
    "email": "test7gmail.com",
    "password": 1234,
    "isAdmin": true
}
###
POST  http://localhost:8888/auth/login
Content-Type: application/json

{
    
    "email": "test1@gmail.com",
    "password": "1234"
    
}

###

POST http://localhost:8888/auth/register
Content-Type: application/json

{
    "username": "test10",
    "email" : "test10@gmail.com",
    "password": "1234"
}

###


GET   http://localhost:8888/auth/logout
Content-Type: application/json


###
PATCH  http://localhost:8888/admin/update/b13b493a-cb91-442b-8f20-65bd7666d418
Content-Type: application/json

{
    "email" : "my second test"
}

###


/////////////////////////////////// PRODUCTS ROUTES

GET http://localhost:8888/admin/products/all

###

GET http://localhost:8888/admin/product/single/62162ec2d7a7129fa95cd666



###

POST http://localhost:8888/admin/product/add
Content-Type: application/json

{
    "title" : "test add",
    "price": "12330"
}

###

PATCH http://localhost:8888/admin/product/update/62162eb5d7a7129fa95cd66c
Content-type: application/json

{
    "title": "yolo",
    "price": 4
}
###

DELETE http://localhost:8888/admin/product/delete/62162eacd7a7129fa95cd660


