

// USERS ROUTES

GET http://localhost:8888/admin/users/all
//authorization: Bearer eyJhbGciOiJIUzI1NiJ9.dG90bw.KgONxc0wLx4BnFIEOVmpg-SSIc_bE49h8sja7ri7lD0
    

###
GET http://localhost:8888/user/62348a479cee35515846e475

    

###
POST  http://localhost:8888/admin/add
Content-Type: application/json

{
    "name": "test4",
    "email": "test4@gmail.com",
    "password": 1234
}

###

POST http://localhost:8888/admin/register
Content-Type: application/json

{
    "email" : "toto",
    "password": "1234"
}

###

POST   http://localhost:8888/admin/login
Content-Type: application/json

{
    "email" : "toto",
    "password": "1234"
}
###
PATCH  http://localhost:8888/admin/b13b493a-cb91-442b-8f20-65bd7666d418
Content-Type: application/json

{
    "email" : "my second test"
}

###


/////////////////////////////////// PRODUCTS ROUTES

GET http://localhost:8000/product

###

POST http://localhost:8000/product
Content-Type: application/json

{
    "title" : "test559",
    "price": "10"
}

###

PATCH http://localhost:8000/product/62162eb5d7a7129fa95cd66c
Content-type: application/json

{
    "title": "yolo",
    "price": 4
}
###

DELETE http://localhost:8000/product/62162eacd7a7129fa95cd660


